services:
  - type: web
    name: hianime-api
    env: node
    region: oregon
    plan: free
    branch: main
    buildCommand: |
      curl -fsSL https://bun.sh/install | bash
      source ~/.bun/bin/bun
      bun install
    startCommand: bun run start
    envVars:
      - key: NODE_ENV
        value: production
